spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:h2:~/travel
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
#        show_sql: true