spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=Asia/Seoul
    username: triple
    password: travel123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
#        show_sql: true